{"name": "test_url_redirect_with_subdomain_same_as_target[chromium1-https://pentest-ground.com:81//services]", "status": "failed", "statusDetails": {"message": "AssertionError: Page URL expected not to be 'https://pentest-ground.com:81//services.https://pentest-ground.com:81//services'\nActual value: https://pentest-ground.com:81//services.https://pentest-ground.com:81//services \nCall log:\nPageAssertions.not_to_have_url with timeout 5000ms\n  - waiting for locator(\":root\")\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"", "trace": "self = <tests.client.url_redirection.TestForcedURLRedirect object at 0x104614110>\npage = <Page url='https://pentest-ground.com:81//services.https://pentest-ground.com:81//services'>, target_url = 'https://pentest-ground.com:81//services'\n\n    def test_url_redirect_with_subdomain_same_as_target(self, page: Page, target_url):\n        with allure.step(\"Visit site and attempt forced-redirect with subdomain as target\"):\n            forced_redirect_url = target_url+\".\"+target_url\n            page.goto(forced_redirect_url)\n>           expect(page).not_to_have_url(forced_redirect_url), f\"Vulnerability found! Forced redirected to {forced_redirect_url} was successful\"\nE           AssertionError: Page URL expected not to be 'https://pentest-ground.com:81//services.https://pentest-ground.com:81//services'\nE           Actual value: https://pentest-ground.com:81//services.https://pentest-ground.com:81//services \nE           Call log:\nE           PageAssertions.not_to_have_url with timeout 5000ms\nE             - waiting for locator(\":root\")\nE             -   locator resolved to <html>…</html>\nE             -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\nE             -   locator resolved to <html>…</html>\nE             -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\nE             -   locator resolved to <html>…</html>\nE             -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\nE             -   locator resolved to <html>…</html>\nE             -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\nE             -   locator resolved to <html>…</html>\nE             -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\nE             -   locator resolved to <html>…</html>\nE             -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\nE             -   locator resolved to <html>…</html>\nE             -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\nE             -   locator resolved to <html>…</html>\nE             -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\nE             -   locator resolved to <html>…</html>\nE             -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\n\nurl_redirection.py:60: AssertionError"}, "description": "Test for client-side URL redirection", "steps": [{"name": "Visit site and attempt forced-redirect with subdomain as target", "status": "failed", "statusDetails": {"message": "AssertionError: Page URL expected not to be 'https://pentest-ground.com:81//services.https://pentest-ground.com:81//services'\nActual value: https://pentest-ground.com:81//services.https://pentest-ground.com:81//services \nCall log:\nPageAssertions.not_to_have_url with timeout 5000ms\n  - waiting for locator(\":root\")\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"https://pentest-ground.com:81//services.https://pentest-ground.com:81//services\"\n\n", "trace": "  File \"/Users/pablovergara/Desktop/automation/vulcanite/tests/client/url_redirection.py\", line 60, in test_url_redirect_with_subdomain_same_as_target\n    expect(page).not_to_have_url(forced_redirect_url), f\"Vulnerability found! Forced redirected to {forced_redirect_url} was successful\"\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 18245, in not_to_have_url\n    self._sync(\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/playwright/_impl/_assertions.py\", line 131, in not_to_have_url\n    await self._not.to_have_url(urlOrRegExp, timeout)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/playwright/_impl/_assertions.py\", line 120, in to_have_url\n    await self._expect_impl(\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/playwright/_impl/_assertions.py\", line 70, in _expect_impl\n    raise AssertionError(\n"}, "start": 1716688231224, "stop": 1716688236497}], "parameters": [{"name": "browser_name", "value": "'chromium'"}, {"name": "target_url", "value": "'https://pentest-ground.com:81//services'"}], "start": 1716688231224, "stop": 1716688236499, "uuid": "b33b16a6-0d54-4a7b-b37a-d1863cfc3161", "historyId": "be8547c6b2623d3283ee39d661da13ce", "testCaseId": "f07bc9718366f02b1a84d865a812c4aa", "fullName": "tests.client.url_redirection.TestForcedURLRedirect#test_url_redirect_with_subdomain_same_as_target", "labels": [{"name": "severity", "value": "critical"}, {"name": "tag", "value": "security"}, {"name": "parentSuite", "value": "tests.client"}, {"name": "suite", "value": "url_redirection"}, {"name": "subSuite", "value": "TestForcedURLRedirect"}, {"name": "host", "value": "Pablos-MBP"}, {"name": "thread", "value": "5647-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.client.url_redirection"}], "links": [{"type": "link", "url": "https://owasp.boireau.io/4-web_application_security_testing/11-client-side_testing/04-testing_for_client-side_url_redirect", "name": "Test for client-side URL redirection (WSTG-CLNT-04)"}]}